spring:
  application:
    name: lobi-server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lobi}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    open-in-view: false
logging:
  level:
    org:
      springframework:
        web: info
        security: debug
      hibernate:
        stat: debug
        SQL: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always